### ISSUE TITLE
数据集

### ISSUE THREAD

**Issue by tenglike1997** [xinrongl/naic#1]
请问你有“华为・昇腾杯”AI+遥感影像的数据集吗？如果能够分享，不胜感激。邮箱：893793477@qq.com

**Comment by xinrongl** [comment]
这个比赛数据当时说了只可以用于比赛用途, 不好意思阿

**Comment by xinrongl** [comment]
> 请问你有“华为・昇腾杯”AI+遥感影像的数据集吗？如果能够分享，不胜感激。邮箱：[893793477@qq.com](mailto:893793477@qq.com)

这个比赛数据当时说了只可以用于比赛用途, 不好意思阿
